### ISSUE TITLE
QCLDPCCodeFromGroup error (from gap-forum)

### ISSUE THREAD

**Issue by dimpase** [gap-packages/guava#23]
Date: Fri, 12 Aug 2016 05:52:33 +0000 (UTC)
From: "R.N. Tsai" r_n_tsai@yahoo.com
as reported there:

To: GAP Forum forum@gap-system.org
Subject: [GAP Forum] Error using guava function QCLDPCCodeFromGroup

Dear Forum,
I tried to use the QCLDPCCodeFromGroup defined in the guava package :I used the example given in the documentation :

```
LoadPackage("guava","0",false);
C:=QCLDPCCodeFromGroup(7,2,3); 
```

I get this error :
Error, no method found! For debugging hints type ?Recovery from NoMethodFoundError, no 1st choice method found for `QCLDPCCodeFromGroup' on 3 arguments called from<function "HANDLE_METHOD_NOT_FOUND">( <arguments>
+)
?QCLDPCCodeFromGroup returns the expected information about it, so it seems that gapknows about the function and I do load the guava package.
I'm using this version of GAP under windows.GAP 4.8.3, 19-Mar-2016, build of 2016-03-20 23:48:47 (GMTST)
I got the same error with win32 and win64 versions and under linux.
Thanks for your help,R.N.

---

Forum mailing list
Forum@mail.gap-system.org
http://mail.gap-system.org/mailman/listinfo/forum

**Comment by fingolfin** [comment]
Indeed the guava manual talks about `QCLDPCCodeFromGroup` and uses it in several examples. As to the guava *code*, it declares `QCLDPCCodeFromGroup` as a GAP operation, but then doesn't install methods for it. Even the version shipped with GAP 4.5 has the same issue.

This is quite weird. Did the method installation for `QCLDPCCodeFromGroup` just got lost by accident at some point in the past? Or was it never realy implemented? Or is it avaiable, just under a different name?

**Comment by dimpase** [comment]
It looks as if it wasn't committed at all. Indeed, 
```
d16b09e8 (Joe Fields 2014-03-23 17:03:59 -0400  41) Version 3.6 (06-2008):
d16b09e8 (Joe Fields 2014-03-23 17:03:59 -0400  42)    o Added QCLDPCCodeFromGroup function.
```
claims it's there already in the 2nd commit to repo.
But it's not there at that point.

**Comment by dimpase** [comment]
But its implementation is in the guava3.6 tarball at https://giam.southernct.edu/Guava/
So it can be obtained. Strange, indeed, it's not in the git repo.

**Comment by dimpase** [comment]
I emailed Joe Fields, asking for an explanation.

**Comment by fingolfin** [comment]
Indeed, it was lost between 3.8 and 3.9. No mention of it in CHANGES.guava ?

Perhaps there was a reason and @osj1961 remembers... But if it was an accident, well, PR #77 adds it back.
