### ISSUE TITLE
Switching to releaseTools and releasing GUAVA 3.14

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/guava#28]
[ReleaseTools for GAP packages](https://github.com/fingolfin/ReleaseTools) by @fingolfin is a set of tools to help to release GAP packages hosted on GitHub. @osj1961 would you be interested in using it?

**Comment by osj1961** [comment]
Alexander,

This looks awesome! I definitely will start using it.

-Joe


Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/


________________________________

**Comment by fingolfin** [comment]
To make best use of it, you may want to also switch the guava website to use https://github.com/fingolfin/GitHubPagesForGAP

However, I see you already setup a custom homepage in `gh-pages`, so in order to transfer all content, you'd have to invest some work. Alternatively, you could also adapt your existing website to work with the the `release` script. I haven't tried it, but I think the only thing stopping you from do so right now is that the script assumes that there is a `update.g` GAP script inside `gh-pages`, which it executes. The version of that script in `GitHubPagesForGAP` reads `PackageInfo.g` and extracts things like the version, package name, authors and maintainers etc. to update the website content.

You could simply add an empty file as `update.g`. Or copy and edit the one from `GitHubPagesForGAP` to work with your site, to also generate things like the version etc. in your HTML.

Lastly, with the `release` script, releases are *not* put directly into the website (i.e. they are *not* put inside the package repository; one shouldn't put big binary files into git repositories). Instead, it uses the GitHub release system. All of that is automated by the script, however, it means that you would have to adjust your download links.

Again, `GitHubPagesForGAP` already takes care of that...

So if you want to take advantage of this, it might be easier to simply use `GitHubPagesForGAP`, but adapt it to include your existing custom content.

If you decide you want to try either route, I'll be happy to provide some assistence.

**Comment by alex-konovalov** [comment]
Aha, so in fact https://gap-packages.github.io/guava/ works now and serves the current content of the `gh-pages` branch. We need to decide how much of this will not be covered by the default template and needs to be preserved.

**Comment by fingolfin** [comment]
Note that the default template is just that: A default. One can freely edit it, and also add additional pages. It would even be possible to convert the current index page into a "template", by replacing things like versions and download likes by the respective placeholders.

**Comment by alex-konovalov** [comment]
Let me ask a plain question: so index.md is not autogenerated, I can put any additional text there, and it will be displayed on the page, right? And in case of any further changes in index.md, they of course then should be merged smoothly...

**Comment by fingolfin** [comment]
The file `index.md` is indeed not autogenerated, to the contrary: the final `index.html` is generated from it, i.e. it serves as a template. Moreover, if one does not want to use Markdown, one can also replace `index.md` with an `index.html` file, which then also used as a template (i.e. substitutions are performed to produce the final results).
For details, I recommend reading the documentation for GitHub pages and/or for Jekyll.

**Comment by alex-konovalov** [comment]
@fingolfin Thanks - I've figured out, there is actually nothing tricky in adding any text in markdown, I've added acknowledgements to http://gap-packages.github.io/openmath/ this way. Thus, @osj1961 @wdjoyner I am happy to help you to set up a new website using https://github.com/fingolfin/GitHubPagesForGAP - how much of information from current https://gap-packages.github.io/guava/ you would like to preserve? I can copy and paste text, or I can move that page to a new place and link it from the main page.

**Comment by wdjoyner** [comment]
It's up to Joe Fields, but I'm ok with it if he us.


On Mar 6, 2017 11:38 AM, "Alexander Konovalov" <notifications@github.com>
wrote:

@fingolfin <https://github.com/fingolfin> Thanks - I've figured out, there
is actually nothing tricky in adding any text in markdown, I've added
acknowledgements to http://gap-packages.github.io/openmath/ this way. Thus,
@osj1961 <https://github.com/osj1961> @wdjoyner
<https://github.com/wdjoyner> I am happy to help you to set up a new
website using https://github.com/fingolfin/GitHubPagesForGAP - how much of
information from current https://gap-packages.github.io/guava/ you would
like to preserve? I can copy and paste text, or I can move that page to a
new place and link it from the main page.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gap-packages/guava/issues/28#issuecomment-284453049>,
or mute the thread

**Comment by osj1961** [comment]
Hi Alex,


I like the idea of moving the existing page and providing a link.  That way nothing is lost and we can always update the new page with that info later.


Thanks,

Joe


Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/


________________________________

**Comment by alex-konovalov** [comment]
@osj1961 a testing version of the new guava's website is announced in PR #29 - please have a look (but DON'T merge!)

**Comment by wdjoyner** [comment]
On Thu, Apr 13, 2017 at 5:03 PM, Alexander Konovalov <
notifications@github.com> wrote:

> @osj1961 <https://github.com/osj1961> a testing version of the new
> guava's website is announced in PR #29
> <https://github.com/gap-packages/guava/pull/29> - please have a look (but
> DON'T merge!)
>

The link for me on http://alex-konovalov.github.io/guava/ is wrong. Please
use https://sites.google.com/site/wdjoyner/ instead.

**Comment by alex-konovalov** [comment]
Thanks @wdjoyner - fixed in https://github.com/gap-packages/guava/commit/4ba672519f8d431b02b4526362f91474d0b64381 so this will be picked up in the next release.

**Comment by alex-konovalov** [comment]
@osj1961 @wdjoyner I plan to return to this - will redo PR #29 in this repo with moving the existing page and providing a link, as agreed.

**Comment by alex-konovalov** [comment]
https://gap-packages.github.io/guava/ now available and serves GUAVA 3.13 archive from https://gap-packages.github.io/guava/archives/guava-3.13.tar.gz (just works because the former gh-branch already contained it). We need now to release GUAVA 3.14. Could you please check if there are any changes that must be done for the release?

**Comment by alex-konovalov** [comment]
@osj1961 @wdjoyner now GAP 4.9 beta is out: https://github.com/gap-system/gap/wiki/GAP-4.9-release-notes and we need a release within next 2 months. I am happy to help. Will you be happy for me to publish the release? Do you have any other issues on this tracker that you plan to address in it?

**Comment by osj1961** [comment]
Hi Alexander,


There is one major outstanding bug/issue that should be fixed before a release.  The decoding algorithm for cyclic codes is not working. Hopefully I'll be able to straighten that out by the end of February.  I'm still not sure if it used to work - possibly it wasn't tested sufficiently - or if a GAP change caused the problem...


I haven't done a release yet since the switch to releaseTools.  Maybe you could coach me through it rather than just doing it yourself.


Best,

Joe



Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/


________________________________

**Comment by fingolfin** [comment]
Any news on this? Resp. any help we can offer with anything?

**Comment by fingolfin** [comment]
@osj1961 ping?

**Comment by osj1961** [comment]
Hi Max,

There is an outstanding bug about the decoding of cyclic codes that I had really hoped to address before the

3.14 release.  Unfortunately, I just don't think I'll have the time to do that work before the Summer.  So I guess

a 3.14 release that leaves that as a "known bug" is in order...


I've reserved this weekend for Guava work.  Hopefully I'll be able to work through the releaseTools checklist and make it happen.  If not I'll send you a cry for help Sunday evening.


Sorry for the delay in responding, my plate is overfull!


Best,

Joe


Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/


________________________________

**Comment by alex-konovalov** [comment]
Shall this be closed now?

Unfortunately, I seen only this message, but not no notifications about 3.14, so it went unnoticed. Because you have changed the URL of the package, and have no control over the old URL, one should update it in the package update system - @fingolfin just did it in https://github.com/gap-system/gap-distribution/pull/51 so I hope that it will be picked up tomorrow.

**Comment by alex-konovalov** [comment]
Picked up:
```
* GUAVA - new version 3.14 discovered!!!
  ============================================
  Getting new archives from 
  https://github.com/gap-packages/guava/releases/download/v3.14/guava-3.14
[ ".tar.gz" ]
  unpacking guava-3.14.tar.gz
  Validation of the info file successful!
  Package GUAVA 3.14 from 24/03/2018 has dependencies:
  * GAP >= 4.8.0
  * SuggestedOtherPackages [ [ "SONATA", ">= 2.3" ] ]
  finding text files  . . .

=====================text files==========================
guava-3.14/README.guava
guava-3.14/PackageInfo.g
guava-3.14/README.md
guava-3.14/makedoc.g
guava-3.14/init.g
guava-3.14/CHANGES.guava
guava-3.14/read.g
guava-3.14/tbl/bdtable3.g
guava-3.14/tbl/codes2.g
guava-3.14/tbl/upperbd2.g
guava-3.14/tbl/bdtable4.g
guava-3.14/tbl/codes3.g
guava-3.14/tbl/upperbd3.g
guava-3.14/tbl/codes4.g
guava-3.14/tbl/bdtable2.g
guava-3.14/tbl/refs.g
guava-3.14/tbl/upperbd4.g
guava-3.14/lib/codeman.gd
guava-3.14/lib/setup.g
guava-3.14/lib/matrices.gi
guava-3.14/lib/decoders.gi
guava-3.14/lib/curves.gd
guava-3.14/lib/codemisc.gd
guava-3.14/lib/codecstr.gi
guava-3.14/lib/nordrob.gd
guava-3.14/lib/bounds.gd
guava-3.14/lib/codeword.gi
guava-3.14/lib/codecr.gi
guava-3.14/lib/codeops.gi
guava-3.14/lib/toric.gi
guava-3.14/lib/tblgener.gi
guava-3.14/lib/util.gi
guava-3.14/lib/util2.gd
guava-3.14/lib/codefun.gd
guava-3.14/lib/codenorm.gd
guava-3.14/lib/codegen.gd
guava-3.14/lib/codeman.gi
guava-3.14/lib/curves.gi
guava-3.14/lib/decoders.gd
guava-3.14/lib/matrices.gd
guava-3.14/lib/nordrob.gi
guava-3.14/lib/codecstr.gd
guava-3.14/lib/codemisc.gi
guava-3.14/lib/codeops.gd
guava-3.14/lib/codecr.gd
guava-3.14/lib/codeword.gd
guava-3.14/lib/bounds.gi
guava-3.14/lib/tblgener.gd
guava-3.14/lib/toric.gd
guava-3.14/lib/codefun.gi
guava-3.14/lib/util2.gi
guava-3.14/lib/util.gd
guava-3.14/lib/codegen.gi
guava-3.14/lib/codenorm.gi
guava-3.14/doc/chap9_mj.html
guava-3.14/doc/chapBib_mj.html
guava-3.14/doc/chap8.txt
guava-3.14/doc/chap0_mj.html
guava-3.14/doc/chap9.txt
guava-3.14/doc/chap2.html
guava-3.14/doc/chap3.html
guava-3.14/doc/chap1_mj.html
guava-3.14/doc/chap8_mj.html
guava-3.14/doc/chapInd.html
guava-3.14/doc/chap3_mj.html
guava-3.14/doc/chapInd.txt
guava-3.14/doc/chap4.html
guava-3.14/doc/chap8.html
guava-3.14/doc/nocolorprompt.css
guava-3.14/doc/lefttoc.css
guava-3.14/doc/chap9.html
guava-3.14/doc/chap2_mj.html
guava-3.14/doc/chap5.html
guava-3.14/doc/chap6.html
guava-3.14/doc/chapBib.txt
guava-3.14/doc/chap7_mj.html
guava-3.14/doc/guava_bib.xml.bib
guava-3.14/doc/guava_bib.xml
guava-3.14/doc/chap6_mj.html
guava-3.14/doc/chap7.html
guava-3.14/doc/times.css
guava-3.14/doc/toggless.css
guava-3.14/doc/chap2.txt
guava-3.14/doc/chap3.txt
guava-3.14/doc/chapBib.html
guava-3.14/doc/chap0.html
guava-3.14/doc/chap1.txt
guava-3.14/doc/chap0.txt
guava-3.14/doc/guava.xml
guava-3.14/doc/chap4_mj.html
guava-3.14/doc/manual.css
guava-3.14/doc/chap4.txt
guava-3.14/doc/chap5.txt
guava-3.14/doc/ragged.css
guava-3.14/doc/chap1.html
guava-3.14/doc/chap5_mj.html
guava-3.14/doc/chap7.txt
guava-3.14/doc/chap6.txt
guava-3.14/doc/chapInd_mj.html
guava-3.14/doc/chooser.html
guava-3.14/tst/hadamard.tst
guava-3.14/tst/decoding.tst
guava-3.14/tst/table.tst
guava-3.14/tst/guava.tst
guava-3.14/tst/guava08.tst
guava-3.14/tst/guava05.tst
guava-3.14/tst/guava04.tst
guava-3.14/tst/guava06.tst
guava-3.14/tst/guava07.tst
guava-3.14/tst/guava03.tst
guava-3.14/tst/guava02.tst
guava-3.14/tst/external.tst
guava-3.14/tst/guava01.tst
guava-3.14/tst/testall.g
guava-3.14/src/defs.h
guava-3.14/src/Makefile
guava-3.14/src/leonconv.c
guava-3.14/src/ctjhai/popcount.h
guava-3.14/src/ctjhai/minimum-weight-gf2.c
guava-3.14/src/ctjhai/config.h
guava-3.14/src/ctjhai/types.h
guava-3.14/src/ctjhai/minimum-weight-gf3.h
guava-3.14/src/ctjhai/README
guava-3.14/src/ctjhai/popcount.c
guava-3.14/src/ctjhai/minimum-weight-gf2.h
guava-3.14/src/ctjhai/minimum-weight.c
guava-3.14/src/ctjhai/minimum-weight-gf3.c
guava-3.14/src/leon/install-sh
guava-3.14/src/leon/configure.ac
guava-3.14/src/leon/configure
guava-3.14/src/leon/Makefile
guava-3.14/src/leon/config.guess
guava-3.14/src/leon/missing
guava-3.14/src/leon/config.sub
guava-3.14/src/leon/Makefile.in
guava-3.14/src/leon/aclocal.m4
guava-3.14/src/leon/doc/leons_original_manual.pdf
guava-3.14/src/leon/doc/manual.dvi
guava-3.14/src/leon/doc/readme
guava-3.14/src/leon/doc/manual.pdf
guava-3.14/src/leon/doc/manual.tex
guava-3.14/src/leon/src/inform.c
guava-3.14/src/leon/src/bitmanp.h
guava-3.14/src/leon/src/relator.h
guava-3.14/src/leon/src/wt.h
guava-3.14/src/leon/src/extname.h
guava-3.14/src/leon/src/readgrp.c
guava-3.14/src/leon/src/fndelt.h
guava-3.14/src/leon/src/essentia.h
guava-3.14/src/leon/src/orblist.h
guava-3.14/src/leon/src/orbrefn.c
guava-3.14/src/leon/src/oldcopy.h
guava-3.14/src/leon/src/ccent.h
guava-3.14/src/leon/src/leon_config.h
guava-3.14/src/leon/src/compsg.h
guava-3.14/src/leon/src/readpts.h
guava-3.14/src/leon/src/permgrp.c
guava-3.14/src/leon/src/factor.c
guava-3.14/src/leon/src/cjrndper.c
guava-3.14/src/leon/src/ptstbref.c
guava-3.14/src/leon/src/ptstab.sh
guava-3.14/src/leon/src/generate.c
guava-3.14/src/leon/src/install
guava-3.14/src/leon/src/cputime.c
guava-3.14/src/leon/src/compcrep.h
guava-3.14/src/leon/src/inter.h
guava-3.14/src/leon/src/randobj.c
guava-3.14/src/leon/src/orbdes.h
guava-3.14/src/leon/src/cent.c
guava-3.14/src/leon/src/matauto.sh
guava-3.14/src/leon/src/chbase.h
guava-3.14/src/leon/src/util.c
guava-3.14/src/leon/src/permut.c
guava-3.14/src/leon/src/cstborb.h
guava-3.14/src/leon/src/settoinv.h
guava-3.14/src/leon/src/wtdist.c
guava-3.14/src/leon/src/orbit.c
guava-3.14/src/leon/src/enum.h
guava-3.14/src/leon/src/readdes.c
guava-3.14/src/leon/src/storage.c
guava-3.14/src/leon/src/optsvec.c
guava-3.14/src/leon/src/cinter.c
guava-3.14/src/leon/src/conj.sh
guava-3.14/src/leon/src/cdesauto.h
guava-3.14/src/leon/src/addsgen.c
guava-3.14/src/leon/src/stcs.c
guava-3.14/src/leon/src/code.h
guava-3.14/src/leon/src/Makefile
guava-3.14/src/leon/src/fndinvol.h
guava-3.14/src/leon/src/randgrp.h
guava-3.14/src/leon/src/cmatauto.h
guava-3.14/src/leon/src/field.h
guava-3.14/src/leon/src/csetstab.c
guava-3.14/src/leon/src/stamp-h1
guava-3.14/src/leon/src/cparstab.c
guava-3.14/src/leon/src/primes.h
guava-3.14/src/leon/src/compgrp.c
guava-3.14/src/leon/src/cuprstab.c
guava-3.14/src/leon/src/setimage.sh
guava-3.14/src/leon/src/gcent.sh
guava-3.14/src/leon/src/token.c
guava-3.14/src/leon/src/new.h
guava-3.14/src/leon/src/randschr.c
guava-3.14/src/leon/src/matrix.h
guava-3.14/src/leon/src/readpar.h
guava-3.14/src/leon/src/partn.h
guava-3.14/src/leon/src/errmesg.c
guava-3.14/src/leon/src/copy.c
guava-3.14/src/leon/src/ccommut.h
guava-3.14/src/leon/src/rprique.h
guava-3.14/src/leon/src/leon_config.h.in
guava-3.14/src/leon/src/commut.c
guava-3.14/src/leon/src/setstab.c
guava-3.14/src/leon/src/readper.h
guava-3.14/src/leon/src/desauto.h
guava-3.14/src/leon/src/readme
guava-3.14/src/leon/src/cstrbas.h
guava-3.14/src/leon/src/factor.h
guava-3.14/src/leon/src/permgrp.h
guava-3.14/src/leon/src/readpts.c
guava-3.14/src/leon/src/generate.h
guava-3.14/src/leon/src/ptstbref.h
guava-3.14/src/leon/src/factoria.h
guava-3.14/src/leon/src/cjrndper.h
guava-3.14/src/leon/src/compper.sh
guava-3.14/src/leon/src/oldcopy.c
guava-3.14/src/leon/src/ccent.c
guava-3.14/src/leon/src/orbrefn.h
guava-3.14/src/leon/src/orblist.c
guava-3.14/src/leon/src/compsg.c
guava-3.14/src/leon/src/fndelt.c
guava-3.14/src/leon/src/repimg.h
guava-3.14/src/leon/src/readgrp.h
guava-3.14/src/leon/src/essentia.c
guava-3.14/src/leon/src/group.h
guava-3.14/src/leon/src/inform.h
guava-3.14/src/leon/src/relator.c
guava-3.14/src/leon/src/bitmanp.c
guava-3.14/src/leon/src/readdes.h
guava-3.14/src/leon/src/orbit.h
guava-3.14/src/leon/src/optsvec.h
guava-3.14/src/leon/src/storage.h
guava-3.14/src/leon/src/codeiso.sh
guava-3.14/src/leon/src/wtdist.h
guava-3.14/src/leon/src/cstborb.c
guava-3.14/src/leon/src/util.h
guava-3.14/src/leon/src/swt.h
guava-3.14/src/leon/src/chbase.c
guava-3.14/src/leon/src/cent.h
guava-3.14/src/leon/src/compset.sh
guava-3.14/src/leon/src/permut.h
guava-3.14/src/leon/src/cjper.sh
guava-3.14/src/leon/src/inter.c
guava-3.14/src/leon/src/cputime.h
guava-3.14/src/leon/src/compcrep.c
guava-3.14/src/leon/src/orbdes.c
guava-3.14/src/leon/src/randobj.h
guava-3.14/src/leon/src/repinimg.h
guava-3.14/src/leon/src/randpts.h
guava-3.14/src/leon/src/chbase.sh
guava-3.14/src/leon/src/token.h
guava-3.14/src/leon/src/cparstab.h
guava-3.14/src/leon/src/cuprstab.h
guava-3.14/src/leon/src/compgrp.h
guava-3.14/src/leon/src/primes.c
guava-3.14/src/leon/src/field.c
guava-3.14/src/leon/src/desiso.sh
guava-3.14/src/leon/src/cmatauto.c
guava-3.14/src/leon/src/randgrp.c
guava-3.14/src/leon/src/csetstab.h
guava-3.14/src/leon/src/groupio.h
guava-3.14/src/leon/src/addsgen.h
guava-3.14/src/leon/src/cdesauto.c
guava-3.14/src/leon/src/matiso.sh
guava-3.14/src/leon/src/cinter.h
guava-3.14/src/leon/src/code.c
guava-3.14/src/leon/src/stcs.h
guava-3.14/src/leon/src/desauto.c
guava-3.14/src/leon/src/ncl.sh
guava-3.14/src/leon/src/cstrbas.c
guava-3.14/src/leon/src/parimage.sh
guava-3.14/src/leon/src/commut.h
guava-3.14/src/leon/src/codeauto.sh
guava-3.14/src/leon/src/readper.c
guava-3.14/src/leon/src/setstab.h
guava-3.14/src/leon/src/rprique.c
guava-3.14/src/leon/src/ccommut.c
guava-3.14/src/leon/src/matrix.c
guava-3.14/src/leon/src/randschr.h
guava-3.14/src/leon/src/new.c
guava-3.14/src/leon/src/parstab.sh
guava-3.14/src/leon/src/errmesg.h
guava-3.14/src/leon/src/copy.h
guava-3.14/src/leon/src/readpar.c
guava-3.14/src/leon/src/partn.c

=====================end of the list of text files=======
=====================binary files========================
guava-3.14/configure
guava-3.14/HISTORY.guava
guava-3.14/COPYING.guava
guava-3.14/Makefile.in
guava-3.14/doc/manual.six
guava-3.14/doc/manual.js
guava-3.14/doc/rainbow.js
guava-3.14/doc/manual.pdf
guava-3.14/doc/toggless.js

=====================end of the list of binary files=====
```
