### ISSUE TITLE
Makefile should not hardcode gcc as the compiler

### ISSUE THREAD

**Issue by dimpase** [gap-packages/guava#31]
Note every system has gcc; e.g. OSX "gcc" is actually not gcc, it's some other compiler, clang.
`./configure` should figure out whether CC should be cc, gcc...

FreeBSD has switched to clang as the default compiler, and does not have gcc (it can be installed, but, well, it's natural to build GAP and the packages with the default compiler, for various reasons)

**Comment by alex-konovalov** [comment]
As well as it should honour CFLAGS, see #36

**Comment by alex-konovalov** [comment]
@dimpase we have now Travis CI setup - if you want now to try to fix this, you're welcome!

**Comment by dimpase** [comment]
OK, thanks, I'll have a look now.

**Comment by dimpase** [comment]
closed by #37
