### ISSUE TITLE
Small problem compiling in Fedora 26

### ISSUE THREAD

**Issue by enriqueartal** [gap-packages/guava#32]
I got an error when compiling the package; adding a ";" at the end of line 178 of src/leon/src/wtdist.c solves the issue

**Comment by osj1961** [comment]
Hi Enrique,


Thanks for the bug report (and the fix!)  I'm at a loss to explain this; one would expect a missing semicolon in C code would cause a syntax error on any OS w/ any compiler.  Am I right in guessing you would use gcc on Fedora?


Best wishes,

J. E. Fields

Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/


________________________________

**Comment by enriqueartal** [comment]
Hi, Joseph,
Yes, I use gcc. Thanks for your work. I guess I can close it. Best, Enrique.
