### ISSUE TITLE
Setup CI for Windows and macOS ?

### ISSUE THREAD

**Issue by osj1961** [gap-packages/guava#40]
Max Horn points out that Travis can be configured to test on MacOS and Windows as well as Linux

**Comment by fingolfin** [comment]
Travis was replaced by GitHub Actions in PR #56

**Comment by fingolfin** [comment]
... which also does allow testing on macOS and Windows.

**Comment by fingolfin** [comment]
I've made PR #76 to address the macOS part of this. I don't think there is much of a benefit in trying to setup a Windows test; in any case it'd required quite a bit more effort to do.
