### ISSUE TITLE
stale links in manual to old osj1961.github.io/guava site

### ISSUE THREAD

**Issue by osj1961** [gap-packages/guava#47]

**Comment by alex-konovalov** [comment]
Would be nice to make a release, to update them. Also, https://github.com/gap-system/gap/pull/3006 waits for #43 in the release.

**Comment by fingolfin** [comment]
@osj1961 A release of guava with the recent fixes would be super nice, as this is blocking changes in GAP (alternatively, we could make those changes in GAP, and thus break guava, but clearly we'd prefer to avoid that).

If you are busy, I can also do the release for you, the main work is updating the changelog, the rest is just running the release script, right?
