### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/guava#60]
... with the changes that accumulated (at least one bug fix, and the new `License` field).

**Comment by fingolfin** [comment]
@osj1961 can you look into this? Leon's code doesn't build on recent macOS anymore, it needs a fix which is already in this git repository but never reached end users.

Before doing a release, please consider merging the open PRs.

Finally, I could also take care of all this for you, it should require less than 5 minutes total.

**Comment by osj1961** [comment]
Hi Max,
I'll work on it this weekend.
Best,
Joe

Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/
________________________________

**Comment by fingolfin** [comment]
Hi @osj1961 do you think everything is ready ? If so, I'd be happy to make the release for you, if you like

**Comment by fingolfin** [comment]
@osj1961 any news on this?

**Comment by osj1961** [comment]
Okay, so I was able to put some time in on guava this weekend.  I tried using the latest version of the ReleaseTools script, which seems to fail prior to pushing anything to github.  I don't know what the "autoheader" it is complaining about is...

fields@elemenopi:~/Desktop/guava$ ../ReleaseTools/release-gap-package 
Using PYTHON = 'python3'
Extracting information from PackageInfo.g...
Package GUAVA 3.16
Building GAP package documentation (using makedoc.g)
Using archive basename guava-3.16
Using GitHub repository gap-packages/guava
Using GitHub username gap-packages
Using branch master
Creating git tag v3.16

Exporting repository content for tag 'v3.16'
Building GAP package documentation for archives (using makedoc.g)
Removing unnecessary files
Generating build system files
+ cd src/leon
+ autoheader
autogen.sh: 7: autoheader: not found

**Comment by osj1961** [comment]
@fingolfin Max, if you could make the release and perhaps let me know what I'm doing wrong it would be appreciated.

**Comment by fingolfin** [comment]
`autoheader` is part of GNU autoconf (I think; maybe it was `automake` instead). Depending on what OS you are using, you can resolve this by installing `automake` and `autoconf` via your package manager.

Anyway, I can take care of the release, sure!

**Comment by fingolfin** [comment]
I've fixed an issue with the date in `PackageInfo.g` in 988624d267f0efd2bb7c48f65759af24305e88ba and made the release.

**Comment by osj1961** [comment]
Hi Max,
Thanks for the offer.  I think I'd prefer to try to get it done myself.  I'm having an ongoing problem (because releases are relatively infrequent), that by the time I'm ready to do a new one, either the process has changed, or I've forgotten what to do!  So, in a nutshell, I need the refresher.
On the other hand, if it's time critical on the GAP side - I may need another week - perhaps you should go ahead...
Best,
Joe

Joseph E. Fields
Professor of Mathematics
Southern Connecticut State University
http://www.southernct.edu/~fields/
________________________________

**Comment by fingolfin** [comment]
Hi @osj1961, actually, the new release discussed on this issue already happened 2022-04-24; and since then we had another 2022-09-05. 

(I wonder if a notification email for this only reached you just now? The same time you wrote your comment, several other people suddenly commented on issues and PRs months past the last activity there, making me wonder if they all received "delayed" notification emails on that day (perhaps GitHub discovered a stuck mail queue somewhere?)
