### ISSUE TITLE
release tarball with auxiliary material

### ISSUE THREAD

**Issue by jgmbenoit** [gap-packages/guava#65]
The tarball https://github.com/gap-packages/guava/releases contains auxiliary material in the `doc` and `src/leon` folders.

**Comment by fingolfin** [comment]
Weird, ReleaseTools should automatically get rid of *.aux and *.log etc. etc. files in `doc` -- unless there is a bug -- and I think there was temporarily a version that had problems on some Unix variants, but the current one *should* work fine everywhere... So I hope this part will be automatically resolved in the next release.

As to auxiliary material in `src/leon`, I assume @jgmbenoit is referring to the `autom4te.cache` subdirectory. This could be easily removed by a line in a `.release` script in the repository (which ReleaseTools executes). I've submitted PR #72 doing just that.

**Comment by fingolfin** [comment]
Resolves in 3.17
